---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "answer.fullname" . }}
  labels:
    {{- include "answer.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  type: ClusterIP
  ports:
    - name: answer
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "answer.selectorLabels" . | nindent 4 }}
