---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: answer
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  selector:
    matchLabels:
      {{- include "answer.labels" . | nindent 6 }}
  serviceName: answer
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "answer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: answer
          image: nginx:stable
          ports:
            - containerPort: 80
              name: answer-ui
          volumeMounts:
            - name: config
              mountPath: "/etc/answer.yaml"
              subPath: default.yaml
      volumes:
        - name: config
          configMap:
            name: answer-config
